# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Topai < Formula
  desc "Topai is an AI-powered terminal process monitor written in Go that combines real-time system monitoring with intelligent analysis. Watch your CPU and memory usage, then use AI providers like Claude, GPT-5, or Gemini to analyze whether high-resource processes are stuck or legitimately busy, all through a beautiful interactive terminal interface."
  homepage ""
  version "1.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Brownei/homebrew-topai/releases/download/v1.0.0/homebrew-topai_1.0.0_darwin_amd64.tar.gz"
      sha256 "d04753e9d9a75ec7b6194f6d9c9f1ddee0294d547d520357e2cd8d68c30c9331"

      def install
        bin.install "topai"
      end
    end
    on_arm do
      url "https://github.com/Brownei/homebrew-topai/releases/download/v1.0.0/homebrew-topai_1.0.0_darwin_arm64.tar.gz"
      sha256 "33146248fa6b922ff2937b707f6b04474782e7543354010701c5ff2e004d592f"

      def install
        bin.install "topai"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Brownei/homebrew-topai/releases/download/v1.0.0/homebrew-topai_1.0.0_linux_amd64.tar.gz"
        sha256 "3181d555b1c5efe4f273e873afbd4467e3990ee7339065105809c3efd6e95602"

        def install
          bin.install "topai"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/Brownei/homebrew-topai/releases/download/v1.0.0/homebrew-topai_1.0.0_linux_armv6.tar.gz"
        sha256 "4a985124ece9c778cad153229b904a3ab4f533901a3df195ef8c9dc266434589"

        def install
          bin.install "topai"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Brownei/homebrew-topai/releases/download/v1.0.0/homebrew-topai_1.0.0_linux_arm64.tar.gz"
        sha256 "929ae4b87c885b2fe1aa830ecf5968511de26f29a8c1fece40d87d35b016a21e"

        def install
          bin.install "topai"
        end
      end
    end
  end

  test do
    system "#{bin}/topai --version"
  end
end
